import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Poppins = localFont({
  src: "./fonts/poppins-light-webfont.woff2",
  variable: "--font-geist-poppins",
  weight: "100 200 300 400 500 600 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${Poppins.variable}  antialiased`}>{children}</body>
    </html>
  );
}
